-- public.usuarios definition
-- Drop table
-- DROP TABLE usuarios;
CREATE TABLE usuarios (
                          id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                          last_name varchar NOT NULL,
                          "name" varchar NOT NULL,
                          "password" varchar NOT NULL,
                          email varchar NOT NULL,
                          birth_day date NOT NULL,
                          active bool DEFAULT true NOT NULL,
                          created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                          updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                          "uuid" uuid NULL,
                          "planeta" varchar NULL,
                          CONSTRAINT usuarios_pk PRIMARY KEY (id)
);
-- Permissions
ALTER TABLE usuarios OWNER TO postgres;
GRANT ALL ON TABLE usuarios TO postgres;